name: hope_pulse
description: "نبض الأمل - تطبيق التبرعات والرسائل الصوتية الإنسانية المكتوب بـ Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  record: ^7.1.1
  audioplayers: ^5.2.1
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
dependency_overrides:
  record: ^5.2.1
  record_platform_interface: 1.6.0
